K                                                                             BestRun         LogL_Mean          LogL_Min          LogL_Max          DLK1          DLK2       FST/FIS
1  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_1_R_1" -2.4776698799E+06 -2.4776698799E+06 -2.4776698799E+06             -             -  8.827118E-01
2  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_2_R_1" -2.2390204476E+06 -2.2390204476E+06 -2.2390204476E+06  1.011936E-01  1.215472E+00  2.033192E-01
3  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_3_R_1" -2.1844136699E+06 -2.1844136699E+06 -2.1844136699E+06  2.468977E-02  1.904059E+00  1.724398E-01
4  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_4_R_1" -2.1868818662E+06 -2.2020545328E+06 -2.1830886996E+06  6.067405E-04  7.575905E-01  5.359839E-02
5  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_5_R_2" -2.1945995729E+06 -2.2007286775E+06 -2.1905082631E+06 -3.392889E-03             -  4.476113E-02

      Method      Best_K
        DLK2           3
     FST/FIS           1


Summary of clustering & admixture analyses of each run: 10 replicates for K = 1 to 5
K Run                                                                                File Time(C) Iter(C)           LogL(C) Time(A) Iter(A)            Tol(A)
1   1  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_1_R_1"       0       0 -2.4776698799E+06       0       1  0.0000000000E+00
1   2  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_1_R_2"       0       0 -2.4776698799E+06       0       1  0.0000000000E+00
1   3  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_1_R_3"       0       0 -2.4776698799E+06       0       1  0.0000000000E+00
1   4  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_1_R_4"       0       0 -2.4776698799E+06       0       1  0.0000000000E+00
1   5  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_1_R_5"       0       0 -2.4776698799E+06       0       1  0.0000000000E+00
1   6  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_1_R_6"       0       0 -2.4776698799E+06       0       1  0.0000000000E+00
1   7  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_1_R_7"       0       0 -2.4776698799E+06       0       1  0.0000000000E+00
1   8  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_1_R_8"       0       0 -2.4776698799E+06       1       1  0.0000000000E+00
1   9  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_1_R_9"       0       0 -2.4776698799E+06       0       1  0.0000000000E+00
1  10 "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_1_R_10"       0       0 -2.4776698799E+06       1       1  0.0000000000E+00
2   1  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_2_R_1"       4    4400 -2.2390204476E+06       7      23  1.9433032179E-08
2   2  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_2_R_2"       1    1458 -2.2390204476E+06       7      23  1.9433032179E-08
2   3  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_2_R_3"       3    4146 -2.2390204476E+06       8      23  1.9433032179E-08
2   4  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_2_R_4"       5    5827 -2.2390204476E+06       7      23  1.9433032179E-08
2   5  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_2_R_5"       6    6117 -2.2390204476E+06       7      23  1.9433032179E-08
2   6  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_2_R_6"       1    1469 -2.2390204476E+06       8      23  1.9433032179E-08
2   7  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_2_R_7"       3    3454 -2.2390204476E+06       7      23  1.9433032179E-08
2   8  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_2_R_8"       4    3762 -2.2390204476E+06       7      23  1.9433032179E-08
2   9  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_2_R_9"       1    1460 -2.2390204476E+06       7      23  1.9433032179E-08
2  10 "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_2_R_10"       3    2677 -2.2390204476E+06       7      23  1.9433032179E-08
3   1  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_3_R_1"       8    8579 -2.1844136699E+06      23      51  8.4834945268E-08
3   2  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_3_R_2"      10    9254 -2.1844136699E+06      22      51  8.4834945268E-08
3   3  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_3_R_3"      11   10610 -2.1844136699E+06      23      51  8.4834945268E-08
3   4  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_3_R_4"      11   10488 -2.1844136699E+06      22      51  8.4834945268E-08
3   5  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_3_R_5"       6    6805 -2.1844136699E+06      23      51  8.4834945268E-08
3   6  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_3_R_6"       3    3898 -2.1844136699E+06      22      51  8.4834945268E-08
3   7  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_3_R_7"       4    4221 -2.1844136699E+06      22      51  8.4834945268E-08
3   8  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_3_R_8"       3    2178 -2.1844136699E+06      22      51  8.4834945268E-08
3   9  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_3_R_9"      10    9919 -2.1844136699E+06      23      51  8.4834945268E-08
3  10 "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_3_R_10"       7    7234 -2.1844136699E+06      22      51  8.4834945268E-08
4   1  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_4_R_1"      31   24624 -2.1830886996E+06      27      51  1.8294973875E-07
4   2  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_4_R_2"      20   16624 -2.1830886996E+06      27      51  1.8294973875E-07
4   3  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_4_R_3"      32   24838 -2.2020545328E+06      28      51  1.2212493051E-07
4   4  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_4_R_4"      18   15452 -2.1830886996E+06      27      51  1.8294973875E-07
4   5  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_4_R_5"      34   26123 -2.2020545328E+06      29      51  1.2212493051E-07
4   6  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_4_R_6"      12   11100 -2.1830886996E+06      26      51  1.8294973875E-07
4   7  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_4_R_7"      19   16387 -2.1830886996E+06      27      51  1.8294973875E-07
4   8  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_4_R_8"      26   21564 -2.1830886996E+06      27      51  1.8294973875E-07
4   9  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_4_R_9"      26   20798 -2.1830886996E+06      27      51  1.8294973875E-07
4  10 "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_4_R_10"      29   23144 -2.1830886996E+06      26      51  1.8294973875E-07
5   1  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_5_R_1"      54   39247 -2.2007286775E+06      31      51  2.0520099580E-07
5   2  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_5_R_2"      34   26442 -2.1905082631E+06      31      56  7.5337947633E-08
5   3  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_5_R_3"      38   29513 -2.1905082631E+06      32      56  7.5337947633E-08
5   4  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_5_R_4"      51   35982 -2.1905082728E+06      31      56  7.5337947633E-08
5   5  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_5_R_5"      57   40567 -2.2007286775E+06      31      51  2.0520099580E-07
5   6  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_5_R_6"      34   26244 -2.1905082631E+06      31      56  7.5337947633E-08
5   7  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_5_R_7"      62   42714 -2.1905396942E+06      26      44  7.7756026402E-08
5   8  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_5_R_8"      44   32888 -2.2007286775E+06      31      51  2.0520099580E-07
5   9  "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_5_R_9"      56   39753 -2.2007286775E+06      30      51  2.0520099580E-07
5  10 "/ddnA/work/a_monc/postdoc/xipho_project/PopCluster/popc_xipho/xipho_popc_K_5_R_10"      30   23026 -2.1905082631E+06      32      56  7.5337947633E-08

Notes of columns:
K: Assumed K value
Run: Replicate # for a given K
File: Output file name
Time(C): Running time of clustering analysis in seconds
Iter(C): #Iterates of clustering analysis
LogL(C): Log(likelihood) of clustering analysis
Time(A): Running time of admixture analysis in seconds
Iter(A): #Iterates of admixture analysis
Tol(A) : Tolerance of admixture analysis
